### ISSUE TITLE
signup.php no code for success

### ISSUE THREAD

**Issue by Stephanie0829** [Radiah12/MindSpace#2]
Code not present (check signup sucessful so it may perhaps be optional):
"
                else if(isset($_GET["signup"])&&($_GET["signup"]=="success")){
                    echo '<p class="signupsuccess">Signup successful!</p>';
                }
"

**Comment by filayer** [comment]
<?php
/*
this code has some other lines
if not :
*/

else if(isset($_GET["signup"]) && ($_GET["signup"]=="success")){
echo 'Signup successful!';
}

/*
if not : you can use following code.
*/
if(isset($_GET["signup"]) && ($_GET["signup"]=="success")){
echo 'Signup successful!';
?>
